### ISSUE TITLE
Nothing shows up while generating

### ISSUE THREAD

**Issue by msukharam963** [YingchaojieFeng/PromptMagician#3]
So the code runs perfectly without any issues but while running the front-end the window pops up and while generating the image the image browser just keeps on loading. ANY FIX FOR THAT?

![Screenshot 2024-04-01 100944](https://github.com/YingchaojieFeng/PromptMagician/assets/85776425/57a49ea6-a880-4d95-9248-a50aeefe2859)

**Comment by YingchaojieFeng** [comment]
Hi~
Have you ever checked the output of the back end? You can check the output in "nohup.out" file when running the back end

**Comment by msukharam963** [comment]
D:\Internship\Kintu Designs\StableDiffusionApp\PromptMagician\back-end\server\util.py:46: SyntaxWarning: invalid escape sequence '\.'
  sub_text_list = re.split(',|\.|/|;|\'|`|\||\[|\]|<|>|\?|:|"|\{|\}|\~|!|@|#|\$|%|\^|&|\(|\)|-|=|\_|\+|\uff0c|\u3002|\u3001|\uff1b| | |\u3010|\u3011| |\uff01| |\uff08|\uff09', text)
[Workflow] device cuda
D:\Python\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
cuda:0
Begin to load model

model_index.json:   0%|          | 0.00/541 [00:00<?, ?B/s]
model_index.json: 100%|##########| 541/541 [00:00<?, ?B/s] 
D:\Python\Lib\site-packages\huggingface_hub\file_download.py:149: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\msukh\.cache\huggingface\hub\models--CompVis--stable-diffusion-v1-4. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Fetching 16 files:   0%|          | 0/16 [00:00<?, ?it/s]
Fetching 16 files: 100%|##########| 16/16 [00:00<00:00, 4015.61it/s]

Loading pipeline components...:   0%|          | 0/7 [00:00<?, ?it/s]
Loading pipeline components...:  29%|##8       | 2/7 [00:00<00:01,  3.63it/s]
Loading pipeline components...:  43%|####2     | 3/7 [00:01<00:02,  1.98it/s]
Loading pipeline components...:  57%|#####7    | 4/7 [00:05<00:05,  1.75s/it]
Loading pipeline components...: 100%|##########| 7/7 [00:06<00:00,  1.02s/it]
Loading pipeline components...: 100%|##########| 7/7 [00:06<00:00,  1.01it/s]
Set device
Start inference
 * Serving Flask app 'sd_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5005
 * Running on http://192.168.74.83:5005
Press CTRL+C to quit
Guidance scale sample list: [5.0, 5.5, 6.0, 6.5, 7.0, 7.5, 8.0, 8.5, 9.0, 9.5, 10.0, 10.5, 11.0, 11.5, 12.0, 12.5, 13.0, 13.5, 14.0, 14.5, 15.0, 15.5, 16.0, 16.5, 17.0, 17.5, 18.0, 18.5, 19.0, 19.5, 20.0, 20.5, 21.0, 21.5, 22.0, 22.5, 23.0, 23.5, 24.0, 24.5, 25.0, 25.5, 26.0, 26.5, 27.0, 27.5, 28.0, 28.5, 29.0, 29.5, 30.0]
negative_prompt is None

  0%|          | 0/50 [00:00<?, ?it/s]D:\Python\Lib\site-packages\diffusers\models\attention_processor.py:1244: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  hidden_states = F.scaled_dot_product_attention(

  2%|2         | 1/50 [00:10<08:37, 10.56s/it]
  4%|4         | 2/50 [00:11<04:00,  5.01s/it]
  6%|6         | 3/50 [00:20<05:20,  6.81s/it]
  8%|8         | 4/50 [00:29<05:51,  7.64s/it]
 10%|#         | 5/50 [00:38<06:04,  8.11s/it]
 12%|#2        | 6/50 [00:47<06:08,  8.38s/it]
 14%|#4        | 7/50 [00:56<06:08,  8.56s/it]
 16%|#6        | 8/50 [01:05<06:04,  8.69s/it]
 18%|#8        | 9/50 [01:14<05:59,  8.76s/it]
 20%|##        | 10/50 [01:23<05:52,  8.81s/it]
 22%|##2       | 11/50 [01:32<05:44,  8.84s/it]
 24%|##4       | 12/50 [01:40<05:36,  8.86s/it]
 26%|##6       | 13/50 [01:49<05:28,  8.88s/it]
 28%|##8       | 14/50 [01:58<05:20,  8.89s/it]
 30%|###       | 15/50 [02:07<05:11,  8.90s/it]
 32%|###2      | 16/50 [02:16<05:02,  8.90s/it]
 34%|###4      | 17/50 [02:25<04:53,  8.90s/it]
 36%|###6      | 18/50 [02:34<04:44,  8.90s/it]
 38%|###8      | 19/50 [02:43<04:35,  8.90s/it]
 40%|####      | 20/50 [02:52<04:26,  8.90s/it]
 42%|####2     | 21/50 [03:01<04:18,  8.90s/it]
 44%|####4     | 22/50 [03:10<04:09,  8.90s/it]
 46%|####6     | 23/50 [03:18<04:00,  8.91s/it]
 48%|####8     | 24/50 [03:27<03:51,  8.90s/it]
 50%|#####     | 25/50 [03:36<03:42,  8.90s/it]
 52%|#####2    | 26/50 [03:45<03:33,  8.91s/it]
 54%|#####4    | 27/50 [03:54<03:24,  8.91s/it]
 56%|#####6    | 28/50 [04:03<03:15,  8.90s/it]
 58%|#####8    | 29/50 [04:12<03:06,  8.90s/it]
 60%|######    | 30/50 [04:21<02:58,  8.90s/it]
 62%|######2   | 31/50 [04:30<02:49,  8.90s/it]
 64%|######4   | 32/50 [04:39<02:40,  8.90s/it]
 66%|######6   | 33/50 [04:47<02:31,  8.90s/it]
 68%|######8   | 34/50 [04:56<02:22,  8.90s/it]
 70%|#######   | 35/50 [05:05<02:13,  8.90s/it]
 72%|#######2  | 36/50 [05:14<02:04,  8.90s/it]
 74%|#######4  | 37/50 [05:23<01:55,  8.90s/it]
 76%|#######6  | 38/50 [05:32<01:46,  8.90s/it]
 78%|#######8  | 39/50 [05:41<01:37,  8.90s/it]
 80%|########  | 40/50 [05:50<01:28,  8.90s/it]
 82%|########2 | 41/50 [05:59<01:20,  8.90s/it]
 84%|########4 | 42/50 [06:08<01:11,  8.90s/it]
 86%|########6 | 43/50 [06:16<01:02,  8.90s/it]
 88%|########8 | 44/50 [06:25<00:53,  8.90s/it]
 90%|######### | 45/50 [06:34<00:44,  8.90s/it]
 92%|#########2| 46/50 [06:43<00:35,  8.90s/it]
 94%|#########3| 47/50 [06:52<00:26,  8.90s/it]
 96%|#########6| 48/50 [07:01<00:17,  8.90s/it]
 98%|#########8| 49/50 [07:10<00:08,  8.90s/it]
100%|##########| 50/50 [07:19<00:00,  8.90s/it]
100%|##########| 50/50 [07:19<00:00,  8.78s/it]
[Infer time: 493.2535514831543]
127.0.0.1 - - [02/Apr/2024 09:51:29] "GET /sd?epo=1&device_id=0&scale_left=5.0&scale_right=30.0&prompt=astronaut+in+ocean&negative_prompt= HTTP/1.1" 200 -


THIS IS THE OUTPUT IN "nohup.out"
AND THIS IS IN TERMINAL AFTER "server.py" is executed.

[Workflow] device cuda
Start to load dataset from poloclub/diffusiondb...
D:\Python\Lib\site-packages\datasets\load.py:1454: FutureWarning: The repository for poloclub/diffusiondb contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/poloclub/diffusiondb
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(
Saving the dataset (6/6 shards): 100%|██████████████████████████████████████████████████████████████| 5000/5000 [00:11<00:00, 437.30 examples/s]
Dataset({
    features: ['image', 'prompt', 'seed', 'step', 'cfg', 'sampler', 'width', 'height', 'user_name', 'timestamp', 'image_nsfw', 'prompt_nsfw'],   
Start to load features from cache...
 * Serving Flask app 'server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5001
 * Running on http://192.168.74.83:5001
Press CTRL+C to quit
url: http://127.0.0.1:5005/sd?epo=1&device_id=0&scale_left=5.0&scale_right=30.0&prompt=astronaut+in+ocean&negative_prompt=
D:\Python\Lib\site-packages\torch\nn\functional.py:5476: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:263.)
  attn_output = scaled_dot_product_attention(q, k, v, attn_mask, dropout_p, is_causal)
text_features torch.Size([1, 512])
[2024-04-02 09:51:31,433] ERROR in app: Exception on /image_overview [GET]
Traceback (most recent call last):
  File "D:\Python\Lib\site-packages\flask\app.py", line 2528, in wsgi_app     
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "D:\Internship\Kintu Designs\StableDiffusionApp\PromptMagician\back-end\server\server.py", line 80, in get_image_overview
    db_item = dataset['train'][db_id_list[index]]
              ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
_getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Lib\site-packages\datasets\formatting\formatting.py", line 583, in query_table
    _check_valid_index_key(key, size)
  File "D:\Python\Lib\site-packages\datasets\formatting\formatting.py", line 526, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 55853 is out of bounds for size 5000
127.0.0.1 - - [02/Apr/2024 09:51:31] "GET /image_overview?prompt=astronaut+in+ocean&negativePrompt=&guidanceScale=5,30&numberOfGeneration=1 HTTP/1.1" 500 -

**Comment by YingchaojieFeng** [comment]
IndexError: Invalid key: 55853 is out of bounds for size 5000

I guess the error is caused by the mismatch of the dataset. The preprocessed data is based on DiffusionDB 2m_first_100k.
If you want to use a different version of the dataset, you need to preprocess it by referring to the [workflow.py](https://github.com/YingchaojieFeng/PromptMagician/blob/main/back-end/server/workflow.py) (Step 3 in README.md)
<img width="1097" alt="截屏2024-04-02 14 18 06" src="https://github.com/YingchaojieFeng/PromptMagician/assets/40166863/659c400c-e155-4aa4-940b-e1447b4fe1e5">

**Comment by msukharam963** [comment]
Thanks for the help. It is working now.
