### ISSUE TITLE
Colab error

### ISSUE THREAD

**Issue by Elham-Keshavarz** [YingchaojieFeng/PromptMagician#6]
Hi
I'm trying to run your project in google colab pro, but after running download.py command, after the data_set is downloaded, I get this error.
Error : 
Using the latest cached version of the module from /root/.cache/huggingface/modules/datasets_modules/datasets/poloclub--diffusiondb/cc0d46ebdb643f128755f0d71d154eb1456672b3c5a7d70b2d666337fa6ac9f6 (last modified on Fri Dec  6 14:50:42 2024) since it couldn't be found locally at poloclub/diffusiondb., or remotely on the Hugging Face Hub.
Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1759, in load_dataset
    builder_instance = load_dataset_builder(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1496, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1218, in dataset_module_factory
    raise e1 from None
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1185, in dataset_module_factory
    raise e
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1158, in dataset_module_factory
    dataset_info = hf_api_dataset_info(
  File "/usr/local/lib/python3.10/dist-packages/datasets/utils/_hf_hub_fixes.py", line 152, in dataset_info
    return hf_api.dataset_info(repo_id, revision=revision, timeout=timeout, use_auth_token=use_auth_token)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 2601, in dataset_info
    headers = self._build_hf_headers(token=token)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/hf_api.py", line 9484, in _build_hf_headers
    return build_hf_headers(
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_headers.py", line 124, in build_hf_headers
    token_to_send = get_token_to_send(token)
  File "/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_headers.py", line 145, in get_token_to_send
    if isinstance(token, str):
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 625, in __str__
    return self._str
AttributeError: 'PosixPath' object has no attribute '_str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/pathlib.py", line 632, in __fspath__
    return str(self)
  File "/usr/lib/python3.10/pathlib.py", line 627, in __str__
    self._str = self._format_parsed_parts(self._drv, self._root,
  File "/usr/lib/python3.10/pathlib.py", line 613, in _format_parsed_parts
    return cls._flavour.join(parts)
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 1290, in exists
    self.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/pathlib.py", line 632, in __fspath__
    return str(self)
  File "/usr/lib/python3.10/pathlib.py", line 625, in __str__
    return self._str
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 587, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python3.10/pathlib.py", line 67, in parse_parts
    drv, root, rel = self.splitroot(part)
  File "/usr/lib/python3.10/pathlib.py", line 240, in splitroot
    if part and part[0] == sep:
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 587, in _parse_args
    return cls._flavour.parse_parts(parts)
  File "/usr/lib/python3.10/pathlib.py", line 61, in parse_parts
    it = reversed(parts)
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 594, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 575, in _parse_args
    if isinstance(a, PurePath):
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 960, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 593, in _from_parts
    self = object.__new__(cls)
RecursionError: maximum recursion depth exceeded while calling a Python object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
  File "/usr/lib/python3.10/pathlib.py", line 959, in __new__
    cls = WindowsPath if os.name == 'nt' else PosixPath
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1741, in load_dataset
    if Path(path, config.DATASET_STATE_JSON_FILENAME).exists():
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
  File "/usr/local/lib/python3.10/dist-packages/datasets/load.py", line 1734, in load_dataset
    if ignore_verifications != "deprecated":
RecursionError: maximum recursion depth exceeded in comparison

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 12, in load_data
    dataset = load_dataset('poloclub/diffusiondb', '2m_first_100k')
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 15, in <module>
    load_data()
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 14, in load_data
    load_data()
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 14, in load_data
    load_data()
  File "/content/PromptMagician/back-end/diffusionDB/download.py", line 14, in load_data
    load_data()
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded

can you help me with it.
best regards

**Comment by YingchaojieFeng** [comment]
Hi~
Have you ever checked whether your download is completed? 
Based on the error report "Using the latest cached version ... since it couldn't be found locally at poloclub/diffusiondb., or remotely on the Hugging Face Hub", I think the download may not be completed.
You can check your network connection or retry the download process following the guideline of "https://huggingface.co/datasets/poloclub/diffusiondb#method-1-using-hugging-face-datasets-loader"

Good luck!
Best

**Comment by Elham-Keshavarz** [comment]
Thanks for your quick response!
It seems like the dataset was already downloaded, but it still got stuck in a catch & error loop to call the "load_data()" method
